name: BreakOut
display_name: Range breakout 1.0
enabled: true
total_strategy_capital: 67500
positioning: risk
holiday_calendar: us

market_hours:
  sessions:
    Monday:
      open_time: "01:05"
      close_time: "23:55"
    Tuesday:
      open_time: "01:05"
      close_time: "23:55"
    Wednesday:
      open_time: "01:05"
      close_time: "23:55"
    Thursday:
      open_time: "01:05"
      close_time: "23:55"
    Friday:
      open_time: "01:05"
      close_time: "23:55"
    Saturday:
      open_time: "00:00"
      close_time: "00:00"
    Sunday:
      open_time: "00:00"
      close_time: "00:00"

assets:
  - symbol: XAUUSD
    open_min: 365
    close_min: 1135
    range_open_min: 185
    range_close_min: 365
    reward_risk_ratio: 1.5
    range_stop_loss: false
    range_size_restricted: false
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 100

  - symbol: USDJPY
    open_min: 360
    close_min: 1080
    range_open_min: 180
    range_close_min: 360
    range_stop_loss: true
    range_size_restricted: false
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 100

  - symbol: US30.cash
    open_min: 965
    close_min: 1255
    range_open_min: 815
    range_close_min: 965
    range_stop_loss: false
    range_size_restricted: false
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 50

  - symbol: GBPUSD
    open_min: 690
    close_min: 1080
    range_open_min: 200
    range_close_min: 690
    range_stop_loss: true
    range_size_restricted: false
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 25

  - symbol: US500.cash
    open_min: 965
    close_min: 1255
    range_open_min: 815
    range_close_min: 965
    range_stop_loss: false
    range_size_restricted: false
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 25
    
  - symbol: EURUSD
    open_min: 120
    close_min: 1080
    range_open_min: 60
    range_close_min: 120
    reward_risk_ratio: 1.5
    range_stop_loss: false
    range_size_restricted: true
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 50

  - symbol: GER40.cash
    open_min: 785
    close_min: 1255
    range_open_min: 635
    range_close_min: 785
    range_stop_loss: false
    range_size_restricted: false
    risk_percent: 0.5
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 1
    percent_of_capital: 50
