name: Crypto
display_name: Crypto 1.3
enabled: true
total_strategy_capital: 100000
positioning: risk
holiday_calendar: us

market_hours:
  sessions:
    Monday:
      open_time: "00:00"
      close_time: "00:00"
    Tuesday:
      open_time: "00:00"
      close_time: "00:00"
    Wednesday:
      open_time: "00:00"
      close_time: "00:00"
    Thursday:
      open_time: "00:00"
      close_time: "00:00"
    Friday:
      open_time: "00:00"
      close_time: "00:00"
    Saturday:
      open_time: "01:05"
      close_time: "23:55"
    Sunday:
      open_time: "01:05"
      close_time: "23:55"

assets:
  - symbol: BTCUSD
    open_min: 665
    close_min: 1200
    range_open_min: 425
    range_close_min: 665
    range_stop_loss: false
    risk_percent: 1.0
    reward_risk_ratio: 2
    max_total_trades: 30
    max_buy_trades: 30
    max_sell_trades: 30
    trade_cooldown_minutes: 15
    percent_of_capital: 3

  - symbol: ETHUSD
    open_min: 665
    close_min: 1200
    range_open_min: 425
    range_close_min: 665
    range_stop_loss: false
    risk_percent: 1.0
    reward_risk_ratio: 2
    max_total_trades: 30
    max_buy_trades: 30
    max_sell_trades: 30
    trade_cooldown_minutes: 15
    percent_of_capital: 3

  - symbol: XRPUSD
    open_min: 665
    close_min: 1200
    range_open_min: 425
    range_close_min: 665
    range_stop_loss: false
    risk_percent: 1.0
    reward_risk_ratio: 2
    max_total_trades: 400
    max_buy_trades: 400
    max_sell_trades: 400
    trade_cooldown_minutes: 2
    percent_of_capital: 100