name: GoLongExt
display_name: Go Long Ext 1.0
enabled: true
total_strategy_capital: 67500
positioning: capital
holiday_calendar: us

market_hours:
  sessions:
    Monday:
      open_time: "01:05"
      close_time: "23:55"
    Tuesday:
      open_time: "01:05"
      close_time: "23:55"
    Wednesday:
      open_time: "01:05"
      close_time: "23:55"
    Thursday:
      open_time: "01:05"
      close_time: "23:55"
    Friday:
      open_time: "01:05"
      close_time: "23:55"
    Saturday:
      open_time: "00:00"
      close_time: "00:00"
    Sunday:
      open_time: "00:00"
      close_time: "00:00"

assets:
  - symbol: GER40.cash
    open_min: 605
    close_min: 1370
    range_open_min: 0
    range_close_min: 605
    range_stop_loss: false
    range_size_restricted: false
    max_total_trades: 1
    max_buy_trades: 1
    max_sell_trades: 0
    percent_of_capital: 100
    
   
